services:
  postgres:
    image: postgres:16-alpine
    container_name: m3bd-postgres
    environment:
      POSTGRES_USER: m3bd
      POSTGRES_PASSWORD: m3bd
      POSTGRES_DB: m3bd
    ports:
      - '5432:5432'
    volumes:
      - m3bd_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U m3bd -d m3bd']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: m3bd-redis
    ports:
      - '6379:6379'
    volumes:
      - m3bd_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  m3bd_pg_data:
  m3bd_redis_data:
