services:
  - type: keyvalue
    name: quickmart-redis
    ipAllowList: []
    maxmemoryPolicy: noeviction

  - type: web
    name: quickmartcore-backend
    runtime: node
    branch: dev
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SYNC_ON_START
        value: 'true'
      - key: REDIS_URL
        fromService:
          name: quickmart-redis
          type: keyvalue
          property: connectionString
